version: '3.4'

services:
  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  offerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  cartservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

